/**
 * Injection tokens for analytics repositories
 * Used for dependency injection to enable repository pattern with interfaces
 */
export const ANALYTICS_REPOSITORY_TOKENS = {
  DASHBOARD_ANALYTICS_REPOSITORY: 'DASHBOARD_ANALYTICS_REPOSITORY',
  USER_ANALYTICS_REPOSITORY: 'USER_ANALYTICS_REPOSITORY',
  JOB_ANALYTICS_REPOSITORY: 'JOB_ANALYTICS_REPOSITORY',
  APPLICATION_ANALYTICS_REPOSITORY: 'APPLICATION_ANALYTICS_REPOSITORY',
  COMPANY_ANALYTICS_REPOSITORY: 'COMPANY_ANALYTICS_REPOSITORY',
} as const;
